# The native_modules.rb was moved to core from 15.1.0:
# https://github.com/react-native-community/cli/pull/2547
# https://github.com/microsoft/react-native-macos/issues/2723
require_relative '../node_modules/react-native-macos/scripts/cocoapods/autolinking.rb'

prepare_react_native_project!

target 'sumappmacos-macOS' do
  platform :macos, '11.0'
  use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :hermes_enabled => false,
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)
  end
end
